### ISSUE TITLE
Maybe for Part

### ISSUE THREAD

**Issue by janjelinek** [nonpop/elm-purl#3]
Hi, just idea what I'm missing here.
I would like to have some Url bunch of params as config part for reusing in several places but with some optional params. For example 

```
urlParams = 
    Url.root 
        |> Url.appendParam "mandatoryOne" (Url.string .m)
        |> Url.appendParam "optionalOne" (Url.string .o)
```
So with this I can have only things like 

```Elm
urlParams |> Url.toString {m = "value", o = ""} 
-- "?mandatoryOne=value&o="
``` 

But I would like to have `"?mandatoryOne=value" output. 

I tried to achieve this but it's not possible even with `Url.custom`. 

So something like this (but probably in some better way) would be great.
```
urlParams = 
    Url.root 
        |> Url.appendParam "mandatoryOne" (Url.string .m)
        |> Url.appendParam "optionalOne" (Url.maybeString .o)

urlParams |> Url.toString { m = "value", o = Nothing } 
-- "?mandatoryOne=value"
```

What do you think about it? If you agree I can try prepare some PR.

**Comment by nonpop** [comment]
Seems useful, yes. If you have time to do a PR I'll be happy to check it out!
