### ISSUE TITLE
Dynamically adding a Dict of QueryParts

### ISSUE THREAD

**Issue by barbeque** [nonpop/elm-purl#5]
I've been using `elm-purl` for two days now and it's saved me a ton of work. Thanks!

However, I'm running into a situation like this:
 * I want to be able to dynamically define 'arguments' to a JSON API (in this case, they're filters)
 * I would like to be able to store the filters as a `List (String, String)` (effectively an informal `Dict`) and then build the list into a query string.
 * There are some query string parameters that will always be there (`page`), so I will set them by hand.

I tried this test:
```elm
module PurlTest exposing (..)

import Expect exposing (Expectation)
import Test exposing (..)

import Purl


type alias Filters = List (String, String)

generateQueryUrl : String -> Int -> Filters -> String
generateQueryUrl baseUrl page filters =
    Purl.customRoot baseUrl
        |> Purl.intQuery "page" .page
        |> appendFilters filters
        |> Purl.toString { page = page }

appendFilters : Filters -> (Purl.Url a) -> (Purl.Url a)
appendFilters filters urlSoFar =
    case filters of
        (key, value) :: rest ->
            let
                updatedUrl = Purl.customQuery key (\_ -> value) urlSoFar
            in
                appendFilters rest updatedUrl
        [] -> urlSoFar

suite : Test
suite =
    describe "Multiple customQuery calls"
        [ test "can generate url with query strings" <|
            \_ ->
                [("cheese", "camembert"), ("bread", "rye")]
                    |> generateQueryUrl "https://sandwiches.com" 4
                    |> Expect.equal "https://sandwiches.com/?page=4&cheese=camembert&bread=rye"
        ]
```

The test fails because it actually generates the URL `https://sandwiches.com/?page=4&cheese=rye&bread=rye` - it seems to reuse the same (last specified) value for each key when the URL is composed into a string with `Purl.toString`.

From reading the Purl code, this is a bit of a surprise - I had assumed passing the lambda in as `stringify` would capture the value for that key/value pair and use that when generating the URL. I'm not entirely sure where this behaviour is coming from.

For now, I've just manually built the query string and then glued it onto the end of the Purl.toString call, but that feels very hacky.

I don't think this is a _bug_ per se in Purl: I think I am misinterpreting the `Purl.maybeCustomQuery` code, or I am trying to use `customQuery` for something it wasn't intended to be used for.

What is the correct "Purl way" of approaching this problem, if there is one?

Thanks!

**Comment by nonpop** [comment]
I think your example should work. I also tried manually evaluating the call to appendFilters and use the result directly, and it works.

In fact, to me it looks like you have actually stumbled on [a compiler bug](https://github.com/elm/compiler/issues/1813). And indeed, changing the tail call `appendFilters rest updatedUrl` to `(\() -> appendFilters rest updatedUrl) ()` seems to fix the problem. Can you confirm this?

**Comment by barbeque** [comment]
Yes, that change fixed it. Thank you for the super-fast and helpful response. I never thought it could be a bug in the compiler's implementation of TCO!

Would you be interested in a PR to add this functionality or something similar? It does bend the strong-typing guarantees of Purl, but I imagine other people have the same problems as I do.

**Comment by nonpop** [comment]
Well, since the point of the library was to improve type & argument order safety, I'm not sure how well it fits. But if you come up with a nice solution, I'm happy to take a look at it. In the meantime, you can write `appendFilters` as a simple fold, which also seems to avoid the TCO bug:
```elm
appendFilters : Filters -> Purl.Url a -> Purl.Url a
appendFilters filters urlSoFar =
    List.foldl (\( key, value ) -> Purl.customQuery key (\_ -> value)) urlSoFar filters
```
Closing the issue since the bug was elsewhere.
